FastFood.UI/Controllers/LancheController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FastFood.Domain.Contracts.Services;
using FastFood.Factory;
using FastFood.Factory.Enum;
using FastFood.Domain.Entities;

namespace FastFood.UI.Controllers
{
    [Route("[controller]"), Route("/")]
    public class LancheController : Controller
    {
        ILancheService serviceLanche = ServiceFactory.GetServiceInstance(EnumServices.Lanche) as ILancheService;
        IIngredienteService serviceIngrediente = ServiceFactory.GetServiceInstance(EnumServices.Ingrediente) as IIngredienteService;

        public IActionResult Index()
        {
            var lanches = serviceLanche.RetornaLanches();

            return View(lanches);
        }

        [Route("Lanche/LancheSelecionado")]
        public IActionResult LancheSelecionado(int id)
        {
            var lanche = serviceLanche.RetornaLanchePorId(id);
            return View(lanche);
        }

        [Route("Lanche/RetornaIngedientes")]
        public JsonResult RetornaIngedientes()
        {
            var ingrediente = serviceIngrediente.RetornaIngredientes();

            return Json(ingrediente);
        }

        [HttpPost]
        [Route("Lanche/PostRetornaLancheCalculado")]
        public JsonResult PostRetornaLancheCalculado(Lanche lanche)
        {
            var lancheAtual = serviceLanche.RetornaLancheCalculado(lanche);

            return Json(lancheAtual);
        }
    }
}

FastFood.UI/Views/Lanche/Index.cshtml
@{
    ViewData["Title"] = "Lanches";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div style="align-content:center;margin-top:100px;">
        <label>LANCHES</label>
    </div>
    <table id="tblLanches" class="table table-striped" style="margin-top:15px;">
        <tr>
            <th>Nome</th>
            <th>Valor</th>
            <th>Escolher</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nome</td>
                <td>@("R$ " + item.Valor)</td>
                <td style="align-content:center;"><a href=@Url.Action("LancheSelecionado", "Lanche", new { id = item.Id }) class="glyphicon glyphicon-ok-circle jsClickConfirm" data-Nome="@item.Nome" style="cursor:pointer;align-content:center;"></a></td>
            </tr>
        }
    </table>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {

            $('#tblLanches').on('click', '.jsClickConfirm', function () {
                var nome = $(this).attr("data-Nome");

                if (confirm('Deseja realmente escolher ' + nome + '?'))
                    return true;

                return false;
             });
        });
    </script>
}

FastFood.UI/Views/Lanche/LancheSelecionado.cshtml
@Model  FastFood.Domain.Entities.Lanche;
@{
    ViewData["Title"] = "LancheSelecionado";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var idsIngredientesLanche = "";

    foreach (var item in Model.IngredienteIds)
    {
        if (idsIngredientesLanche == string.Empty)
        {
            idsIngredientesLanche = item.ToString();
        }
        else
        {
            idsIngredientesLanche = idsIngredientesLanche + "," + item.ToString();
        }
    }
}
<div style="align-content:center;margin-top:50px;">
    <label style="font-weight:bold;">LANCHE SELECIONADO</label>
</div>

<div style="margin-top:30px;">
    <label style="font-weight:normal">Nome do Lanche:</label>
    <label style="font-weight:bold;" id="lblNome">@Model.Nome</label>
</div>
<div style="margin-top:15px;">
    <label style="font-weight:normal;">Valor do Lanche:</label>
    <label style="font-weight:bold;" id="lblValor">@("R$ " + Model.Valor)</label>
</div>
<div style="margin-top:15px;margin-bottom:30px;">
    <label style="font-weight:normal;">Ingredientes para adicionar:</label>
    <select id="ddlIngredientes"></select>
    <button id="btnAdd">Adicionar</button>
</div>
<div style="margin-top:15px;">
    <table id="tblIngredientes" class="table table-striped" style="margin-top:15px;">
        <tr>
            <th>Ingrediente</th>
            <th>Valor</th>
            <th>Ações</th>
        </tr>
        @foreach (var item in Model.Ingredientes)
        {
            <tr>
                <td><input id=hiddenId type=hidden value=@item.Id />@item.Nome</td>
                <td>@("R$ " + item.Valor)</td>
                <td style="align-content:center;"><a class="glyphicon glyphicon-remove-circle jsClickRemover" data-Id="@item.Id" style="cursor:pointer;align-content:center;"></a></td>
            </tr>
        }
    </table>
</div>

<div style="margin-top:15px;">
    <a id="btnVoltar" href="@Url.Action("index")" style="margin-right:50px;">Voltar</a>
    <a id="btnFinalizar" href="@Url.Action("index")">Finalizar pedido</a>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            var listaIngredientes = [];
            var ingredientesSelecionados = [];
            var ingredientesLancheSelecionado = '@idsIngredientesLanche'

            $.ajax({
                url: "/Lanche/RetornaIngedientes",
                success: function (data) {
                    $("#ddlIngredientes").empty();
                    $("#ddlIngredientes").append('<option value=0>Selecione...</option>');
                    $.each(data, function (index, element) {
                        $("#ddlIngredientes").append('<option value="' + element.id + '">' + element.nome + '</option>');
                    });

                    listaIngredientes = data;

                    var ingrAux = ingredientesLancheSelecionado.split(',');

                    for (var i = 0; i < ingrAux.length; i++)
                    {
                        ingredientesSelecionados.push(parseInt(ingrAux[i]));
                    }
                }
            });

            $("#btnAdd").click(function () {
                var valor = 0;

                if ($("#ddlIngredientes").val() == 0) {
                    alert("Selecione um ingrediente!");
                }
                else {

                    ingredientesSelecionados.push(parseInt($("#ddlIngredientes").val()));
                    var valorAux = $('#lblValor').html().replace("R$ ", "");

                    var valorObj = parseFloat(valorAux);

                    $.post("/Lanche/PostRetornaLancheCalculado",
                        { "id": @Model.Id, "ingredienteids": ingredientesSelecionados, "nome": '@Model.Nome', "valor": valorObj },
                                obterCallback
                          );

                    for (var i = 0; i < listaIngredientes.length; i++) {
                        if ($("#ddlIngredientes").val() == listaIngredientes[i].id) {
                            valor = listaIngredientes[i].valor;
                            break;
                        }
                    }

                    $('#tblIngredientes tr:last').after('<tr><td><input id=hiddenId type=hidden value=' + $("#ddlIngredientes").val() + ' />' + $('#ddlIngredientes option:selected').text() + '</td><td>R$ ' + valor + '</td><td style=lign-content:center;><a class="glyphicon glyphicon-remove-circle jsClickRemover" data-Id=' + $("#ddlIngredientes").val() + ' style="cursor:pointer;align-content:center;"></a></td></tr>');
                    $("#ddlIngredientes").val("0");
                }
            });

            $('#tblIngredientes').on('click', '.jsClickRemover', function () {
                var id = parseInt($(this).attr("data-Id"));
                var pos = ingredientesSelecionados.indexOf(id);

                ingredientesSelecionados.splice(pos, 1);

                var valorAux = $('#lblValor').html().replace("R$ ", "");

                var valorObj = parseFloat(valorAux);

                $.post("/Lanche/PostRetornaLancheCalculado",
                { "id": @Model.Id, "ingredienteids": ingredientesSelecionados, "nome": '@Model.Nome', "valor": valorObj },
                    obterCallback
                );

                $(this).closest('tr').remove();
            });

            $('#btnVoltar').click(function () {
                if (confirm('Deseja realmente cancelar o pedido?'))
                    return true;

                return false;
            });

            $('#btnFinalizar').click(function () {
                if (confirm('Deseja realmente finalizar o pedido?'))
                {
                    alert('O seu pedido foi ' + $('#lblNome').html() + '\n no valor total de ' + $('#lblValor').html());

                    return true;
                }

                return false;
            });
        });

        function obterCallback(retorno, status) {
            $('#lblValor').html("R$ " + retorno.valor);
        }
    </script>
}

FastFood.UI/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fast Food</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Lanche" asp-action="Index" class="navbar-brand">Fast Food</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Lanche" asp-action="Index">Lanche</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Fast Food</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>